# Generated by Django 4.2.11 on 2024-05-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('SellerId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('PropertyId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AddressLine1', models.CharField(max_length=255)),
                ('AddressLine2', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255)),
                ('Pin', models.IntegerField()),
                ('State', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('AreaInSqFt', models.IntegerField()),
                ('BHK', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('Brokerage', models.IntegerField(default=0)),
                ('MaintenanceCharge', models.IntegerField(default=0)),
                ('Deposit', models.IntegerField()),
                ('Floor', models.IntegerField()),
                ('PropertyType', models.CharField(max_length=255)),
                ('PostedOn', models.DateField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='RentifyApp.seller')),
            ],
        ),
    ]
